// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/AccessControl.sol";

/**
 * @title ICreditScoreZKForVerifier
 * @notice Minimal interface for the CreditScoreZK contract used by ZKVerifier.
 */
interface ICreditScoreZKForVerifier {
    function updateScoreFromZK(address user, uint256 newScore) external;
}

/**
 * @title ZKVerifier
 * @author CredLink ZK Team
 * @notice Groth16 ZK proof verifier for the CredLink behavioral credit scoring
 *         system. Accepts a proof and three public signals (walletAgeValid,
 *         repaymentValid, scoreOutput) and, upon successful verification,
 *         updates the user's on-chain credit score via CreditScoreZK.
 *
 * @dev For hackathon / development purposes the contract ships with
 *      `productionMode = false`. In mock mode the proof arrays (a, b, c)
 *      are ignored and validation is performed solely on the public signals.
 *
 *      Production: replace the `_groth16Verify` function body with the
 *      verifier generated by snarkjs for your circuit.
 */
contract ZKVerifier is AccessControl {
    // -----------------------------------------------------------------------
    //  State
    // -----------------------------------------------------------------------

    /// @notice Reference to the CreditScoreZK contract.
    ICreditScoreZKForVerifier public creditScoreZK;

    /**
     * @notice When false (default), proof verification uses a simplified mock
     *         that only checks the public signals. Set to true for real
     *         Groth16 verification.
     */
    bool public productionMode = false;

    // -----------------------------------------------------------------------
    //  Events
    // -----------------------------------------------------------------------

    /// @notice Emitted when a ZK proof is successfully verified and the score
    ///         is forwarded to CreditScoreZK.
    /// @param user  The user whose score was updated.
    /// @param score The new credit score derived from the proof.
    event ProofVerified(address indexed user, uint256 score);

    /// @notice Emitted when production mode is toggled.
    /// @param enabled True if production mode is now enabled.
    event ProductionModeUpdated(bool enabled);

    // -----------------------------------------------------------------------
    //  Constructor
    // -----------------------------------------------------------------------

    /**
     * @notice Deploys the ZKVerifier with a reference to the CreditScoreZK contract.
     * @param _creditScoreZK Address of the deployed CreditScoreZK contract.
     */
    constructor(address _creditScoreZK) {
        require(
            _creditScoreZK != address(0),
            "ZKVerifier: credit score is zero address"
        );

        creditScoreZK = ICreditScoreZKForVerifier(_creditScoreZK);
        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
    }

    // -----------------------------------------------------------------------
    //  External — Proof Verification
    // -----------------------------------------------------------------------

    /**
     * @notice Verifies a Groth16 ZK proof and, if valid, updates the user's
     *         credit score on-chain.
     *
     * @dev Public signals layout:
     *        publicSignals[0] = walletAgeValid   (1 = valid, 0 = invalid)
     *        publicSignals[1] = repaymentValid   (1 = valid, 0 = invalid)
     *        publicSignals[2] = scoreOutput      (0-1000)
     *
     *      In mock mode (productionMode == false) the proof components
     *      (a, b, c) are ignored and the function simply checks that both
     *      boolean signals are 1 and the score is within range.
     *
     * @param a             Groth16 proof element A (2 field elements).
     * @param b             Groth16 proof element B (2x2 field elements).
     * @param c             Groth16 proof element C (2 field elements).
     * @param publicSignals The three public inputs [walletAgeValid, repaymentValid, scoreOutput].
     * @param user          The address whose credit score should be updated.
     */
    function verifyAndUpdateScore(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[3] calldata publicSignals,
        address user
    ) external {
        require(user != address(0), "ZKVerifier: user is zero address");

        bool isValid;

        if (!productionMode) {
            // -----------------------------------------------------------------
            //  Mock verification (hackathon / development mode)
            // -----------------------------------------------------------------
            isValid = _mockVerify(publicSignals);
        } else {
            // -----------------------------------------------------------------
            //  Production Groth16 verification
            //  Production: replace with snarkjs generated verifier
            // -----------------------------------------------------------------
            isValid = _groth16Verify(a, b, c, publicSignals);
        }

        require(isValid, "ZKVerifier: invalid proof");

        // --- Forward verified score to CreditScoreZK ---
        creditScoreZK.updateScoreFromZK(user, publicSignals[2]);

        emit ProofVerified(user, publicSignals[2]);
    }

    // -----------------------------------------------------------------------
    //  Admin
    // -----------------------------------------------------------------------

    /**
     * @notice Toggles production mode for proof verification.
     * @dev Only callable by DEFAULT_ADMIN_ROLE.
     * @param enabled True to enable production Groth16 verification, false for mock.
     */
    function setProductionVerifier(
        bool enabled
    ) external onlyRole(DEFAULT_ADMIN_ROLE) {
        productionMode = enabled;
        emit ProductionModeUpdated(enabled);
    }

    // -----------------------------------------------------------------------
    //  Internal — Verification Logic
    // -----------------------------------------------------------------------

    /**
     * @dev Mock verification used during development / hackathon.
     *      Returns true if:
     *        - walletAgeValid == 1
     *        - repaymentValid == 1
     *        - scoreOutput <= 1000
     *
     * @param publicSignals The three public inputs.
     * @return True if the mock checks pass.
     */
    function _mockVerify(
        uint256[3] calldata publicSignals
    ) internal pure returns (bool) {
        return
            publicSignals[0] == 1 &&
            publicSignals[1] == 1 &&
            publicSignals[2] <= 1000;
    }

    /**
     * @dev Placeholder for the real Groth16 verifier.
     *      Production: replace this function body with the on-chain verifier
     *      generated by snarkjs (`snarkjs zkey export solidityverifier`).
     *
     * @param a             Groth16 proof element A.
     * @param b             Groth16 proof element B.
     * @param c             Groth16 proof element C.
     * @param publicSignals The three public inputs.
     * @return True if the proof is valid.
     */
    function _groth16Verify(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[3] calldata publicSignals
    ) internal pure returns (bool) {
        // Silence unused variable warnings in placeholder.
        a;
        b;
        c;
        publicSignals;

        // Production: replace with snarkjs generated verifier
        // This placeholder always returns false to prevent accidental use
        // in production without a real verifier.
        return false;
    }
}
